# Generated by Django 4.0.1 on 2022-02-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('CUPCAKES', 'Cupcakes'), ('THINGS', 'Things')], default='News', max_length=200),
        ),
    ]
