# Generated by Django 4.0.1 on 2022-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='newsstory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
