# Generated by Django 4.0.1 on 2022-02-15 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsstory_options_newsstory_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='newsstory',
            name='updated',
        ),
    ]
